# Generated by Django 4.1.7 on 2023-03-02 14:22

import computers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to=computers.utils.get_category),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='plural_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
