# Generated by Django 4.1.7 on 2023-03-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_memory_product_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=10)),
                ('frequency', models.PositiveIntegerField()),
                ('latency', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='computers.specification'),
        ),
    ]
