# Generated by Django 4.1.7 on 2023-03-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_rename_max_frequency_specification_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='product_slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='company',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='power',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='computers.specification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='computers.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='parameters',
            field=models.JSONField(default=1, verbose_name='Подробные характеристики'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='computers.specification'),
            preserve_default=False,
        ),
    ]
