# Generated by Django 4.1.7 on 2023-03-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0010_remove_category_products_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='details',
        ),
    ]
