# Generated by Django 4.1.7 on 2023-03-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0012_rename_cat_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='computers.specification'),
        ),
    ]
