# Generated by Django 4.1.7 on 2023-03-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0013_alter_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_specification_name', models.CharField(max_length=100)),
                ('specification_name', models.CharField(max_length=100)),
                ('filter_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.category')),
            ],
        ),
    ]
