# Generated by Django 4.1.7 on 2023-03-20 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0015_rename_mainparameters_mainspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.category'),
        ),
    ]
