# Generated by Django 4.1.7 on 2023-03-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0016_specification_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainspecification',
            name='category',
        ),
        migrations.AddField(
            model_name='mainspecification',
            name='feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainspecification',
            name='filter_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
