# Generated by Django 4.1.7 on 2023-03-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0017_remove_mainspecification_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='category',
        ),
        migrations.AddField(
            model_name='mainspecification',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.category'),
        ),
    ]
