# Generated by Django 4.1.7 on 2023-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0019_alter_product_options_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
