# Generated by Django 4.1.7 on 2023-03-24 19:27

import computers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0020_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=computers.utils.get_category_name),
        ),
    ]
