# Generated by Django 4.1.7 on 2023-03-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0022_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
